### ISSUE TITLE
Open all bags behavior

### ISSUE THREAD

**Issue by Yanngo** [jrob8577/Auctionator#67]
There is an option to automatically open all bags when the player uses the auction house.
However, there are many other addons, for instance, ArkInventory that open all the bags at that time. Every time I have to disable it.

Is it possible for Auctionator to check whether the bags have been opened first?

Or is it possible to disable the option across all characters of mine? It seems Auctionator saves the state of all the other options uniformly for all characters except the state of this checkbox.

**Comment by jrob8577** [comment]
Not sure, but I can look into it.  Thanks for the request!

**Comment by jrob8577** [comment]
I've made it such that this selection is saved for all characters, instead of per character.  It's possible to listen for bag opening events, and have the addon track the state of bags, but I think it might be overkill given the enable/disable request.

This change will be made in the upcoming Legion release.

**Comment by jrob8577** [comment]
Thanks @ceylina for the fix! This will be updated in Legion version.
